## 1\. Numpy是什么？[](https://gengzhige-essay.readthedocs.io/docs/01%20%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE/1-5%20Numpy%E6%95%99%E7%A8%8B.html#id1 "永久链接至标题")

**Numerical Python** 的缩写

-   一个开源的Python科学计算库
    
-   使用numpy可以方便的使用数组、矩阵进行计算
    
-   包含线性代数、傅里叶变换、随机数生成等大量函数
    

## 2\. 为什么使用Numpy？[](https://gengzhige-essay.readthedocs.io/docs/01%20%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE/1-5%20Numpy%E6%95%99%E7%A8%8B.html#id2 "永久链接至标题")

对于同样的数值计算任务，使用numpy比直接编写python代码实现 优点：

-   代码更简洁： numpy直接以数组、矩阵为粒度计算并且支持大量的数学函数，而python需要用for循环从底层实现；
    
-   性能更高效： numpy的数组存储效率和输入输出计算性能，比python使用list好很多；numpy的大部分代码都是c语言实现的，这是numpy比python高效的原因
    

numpy是python各种数据科学类库的基础库

-   比如SciPy、Scikit-Learn、tenorflow、paddlepaddle等
    
-   如果不会numpy，这些库的深入理解都会遇到障碍

In [1]:
import numpy as np

In [4]:
#原生语法实现
def _sum(n):
    a=[i**2 for i in range(n)]
    b=[i**3 for i in range(n)]
    c=[a[i]+b[i] for i in range(n)]
    return c
print(_sum(5))

[0, 2, 12, 36, 80]


In [6]:
import numpy as np
#numpy实现
def __sum(n):
    a=np.arange(n)**2
    b=np.arange(n)**3
    return a+b
print(__sum(5))

[ 0  2 12 36 80]


### ndarray对象：[](https://gengzhige-essay.readthedocs.io/docs/01%20%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE/1-5%20Numpy%E6%95%99%E7%A8%8B.html#ndarray "永久链接至标题")

-   numpy的核心数据结构，叫做array就是数组，array对象可以是一维数组，也可以是多维数组
    
-   python的list也可以实现相同的功能，但是array的优势在于性能好，包含数组元数据信息、大量的便捷函数
    
-   成为 Scipy、Pandas、scilit-learn、tensorflow、paddlepaddle等框架的通用底层语言
    
-   numpy的array和python的list的一个区别是它的元素必须都是同一种数据类型，这也是numpy高性能的一个原因
    

### ndarray属性[](https://gengzhige-essay.readthedocs.io/docs/01%20%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE/1-5%20Numpy%E6%95%99%E7%A8%8B.html#id4 "永久链接至标题")

-   shape 返回一个元组 表示array的形状
    
-   ndim 返回一个数字 表示array的维度的数目
    
-   size 返回一个数字 表示array中所有数据元素的数目
    
-   dtype array中元素的数据类型
    
-   itemsize 表示数组中每个元素的字节大小
    

### array本身支持的大量操作和函数[](https://gengzhige-essay.readthedocs.io/docs/01%20%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE/1-5%20Numpy%E6%95%99%E7%A8%8B.html#array "永久链接至标题")

-   直接逐元素的加减乘除等算数操作
    
-   更好用的面向多维的数组索引
    
-   求sum/mean等聚合函数
    
-   线性代数函数、比如求解逆矩阵、求解方程组
    

## 6\. 创建array的方法[](https://gengzhige-essay.readthedocs.io/docs/01%20%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE/1-5%20Numpy%E6%95%99%E7%A8%8B.html#id5 "永久链接至标题")

-   从Python的列表list和嵌套列表创建array
    
-   使用预定函数arange、linspace等创建等差数组
    
-   使用ones、ones\_like、zeros、zeros\_like、empty、empty\_like、full、full\_like、eye等函数创建
    
-   生成随机数的np.random模块创建

In [ ]:
import numpy as np

x= np.array([1,2,3,4,5])
x


array([1, 2, 3, 4, 5])

In [ ]:
y=np.array([
    [1,2,3,4],
    [5,6,6,7]
])
y

array([[1, 2, 3, 4],
       [5, 6, 6, 7]])

In [ ]:
m,n=y.shape
print("{}   {}".format( m,n))
mm=x.shape[0]
print(mm)#返回是数组格式返回选择返回第几维，和size分清
print("数据个数",y.size)#一共有多少个数据
print("维数",y.ndim)#几维

2   4
5
数据个数 8
维数 2


### 使用np.arange(start,stop,step,dtype) 生成等差数组

-   start 表示开始的数（包含） 默认从0开始
    
-   stop 表示结束的数（不包含）
    
-   step 指定步长 默认为1
    
-   dtype 指定数据类型

In [ ]:
a=np.arange(10)
b=np.arange(1,10,2,int)
b

array([1, 3, 5, 7, 9])

In [ ]:
# reshape 可以改变数组的形状
# 将一维数组 改成 2行5列的 2维数组
np.arange(10).reshape(2,5)#需要被整分

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 使用np.linspace(start,stop,num,endpoint) 创建等差数组-指定数量

-   start 起始值
    
-   stop 结束值
    
-   num 要生成的等间隔样例数量，默认为50
    
-   endpoint 序列中是否包含stop值， 默认为true

In [ ]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [ ]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

**使用ones、ones_like、zeros、zeros_like、empty、empty_like、full、full_like、eye等函数创建**

In [ ]:
a=np.ones(10)# 使用ones创建全是1的数组
print("a",a)

b=np.ones((2,4))
print("b",b)

c=np.ones_like(a)# 使用ones_like创建形状相同的数组
print("c",c)

d=np.zeros(10)
print("d",d)

e=np.zeros_like(b)
print("e",e)

# 使用empty创建未初始化的数组
# 注意：数据是未初始化的，里面的值可能是随机值不要用
f=np.empty(10)
print("f",f)

# 使用full创建指定值的数组
g=np.full(10, 666)
print("g",g)

h=np.full((2, 4), 777)
print("h",h)#同样可使用fill_like，请举一反三

# 使用 eye 函数创建 对角线的地方为1，其余的地方为0.
i=np.eye(5)
print("i",i)

a [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
b [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
c [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
d [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
e [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
f [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
g [666 666 666 666 666 666 666 666 666 666]
h [[777 777 777 777]
 [777 777 777 777]]
i [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
np.random.seed(666)#设置种子

In [ ]:
np.random.rand(2,5)# 随机生成 2行5列的2维数组  数据在[0,1)之间
help(np.random.rand)

Help on built-in function rand:

rand(...) method of numpy.random.mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `random_sample`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Examples
    --------
    >>> np.random.rand(3,2)
    arra

In [ ]:
# 生成随机整数  区间范围：[2,5) 左闭右开  包含2不包含5
np.random.randint(2,5)

4

In [ ]:
# 指定shape
np.random.randint(2,5,5)

array([4, 3, 3, 3, 4])

In [ ]:
# 前面的 2， 5 表示 取值的区间范围 [2,5)
# 后面的(2,5) 是指定的shape
np.random.uniform(2,5,(2,5))#uniform生成的是均匀数字

array([[2.72814381, 3.71131018, 3.73320211, 4.67824544, 2.36415632],
       [3.98251619, 2.49377813, 2.28307512, 3.76284321, 4.58043336]])

In [ ]:
np.random.randn(3,4)#标准正态分布的一些数字，均值为0方差为1

array([[-1.44545669, -0.26378654,  1.71971234,  0.4855902 ],
       [ 0.52281208,  1.51131644, -0.82449495,  0.09383679],
       [ 1.75190746, -1.21352598, -0.36490519, -0.61302436]])

In [ ]:
# normal()  可以指定均值和标准差差
np.random.normal(1,10,5)
help(np.random.normal)

Help on built-in function normal:

normal(...) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    .. note::
        New code should use the ``normal`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution

In [ ]:
np.random.normal(5,10,(3,4))

array([[-6.17608559, 16.59436829,  3.62046574, 11.50429911],
       [ 5.42329233, 21.48030724,  4.43405768, 18.13656068],
       [10.03269545, -0.51419175,  9.27638555, -2.22671385]])

In [ ]:
# choice 从给定的数组里 生成随机结果
np.random.choice(5, 3)
# 等同于 np.random.choice(0, 5, 3)  在[0,5)的区间范围内 生成3个数据

array([2, 3, 4])

In [ ]:
print(np.random.choice(5, (2, 3)),'\n')
print(np.random.choice([1,3,5,2,3], 3))

[[2 1 4]
 [2 4 3]] 

[2 5 3]


In [ ]:
# shuffle 把一个数组进行随机排列
# 如果数组是多维的  则只会在第一维度打散数据

a = np.arange(10)
np.random.shuffle(a) 
a

array([6, 5, 7, 1, 9, 8, 3, 2, 4, 0])

In [ ]:
# permutation 把一个数组进行随机排列  或者数字的全排列
print(np.random.permutation(10))
# permutation 与 shuffle 函数功能相同  区别在于：
# 注意 permutation不会更改原来的arr 会返回一个新的copy

**数组索引**
-   基础索引
    
-   神奇索引
    
-   布尔索引

In [ ]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(x[0])
print(x[2:-1])
print(x[2:])

0
[2 3 4 5 6 7 8]
[2 3 4 5 6 7 8 9]


In [ ]:
y=np.arange(20).reshape(4,5)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
print(y[2])#第三行
print('\n',y[:,2])#第三列

[10 11 12 13 14]

 [ 2  7 12 17]


**切片修改会改变原来的数组**



In [ ]:
x=np.arange(10)
x[:2]=114514
x

array([114514, 114514,      2,      3,      4,      5,      6,      7,
            8,      9])

**神奇索引**
就是： 用整数数组进行的索引



In [ ]:
x = np.arange(10)
print(x[[2,3,4]])
indexs =np.array([[0,2],[1,3]])
print(x[indexs])
print(indexs)



[2 3 4]
[[0 2]
 [1 3]]
[[0 2]
 [1 3]]


In [4]:
arr=np.random.randint(1,100,10)
# arr.argsort() 会返回排序后的索引index
# 取最大值对应的3个下标
print(arr,arr.argsort()[-3:],arr[arr.argsort()[-3:]])

[ 5 23 12 27 59 77 66 12  5 51] [4 6 5]


In [8]:
Y = np.arange(20).reshape(4, 5)
print(Y,'\n')
print(Y[[0,2]],'\n')
print(Y[:,[0,2]],'\n')#指定列
print([[0,2,3],[1,2,3]],'\n')
print(# 同时指定行列
Y[[0,2,3],[1,2,3]])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

[[ 0  1  2  3  4]
 [10 11 12 13 14]] 

[[ 0  2]
 [ 5  7]
 [10 12]
 [15 17]] 

[[0, 2, 3], [1, 2, 3]] 

[ 1 12 18]


In [16]:
arr=np.arange(10)

print(arr>5)
arr[arr<=5]=0
arr[arr>5]=1
help(arr[x>5])
print(arr)

[False False False False False False  True  True  True  True]
Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of cr

In [19]:
Y = np.arange(20).reshape(4, 5)
print(Y>5)
print(Y[Y>5])
print(Y[:, 3])
print(Y[:,3]>5)

[[False False False False False]
 [False  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 3  8 13 18]
[False  True  True  True]


In [20]:
# 把第3列大于5的行数据筛选出来
Y[:, 3][Y[:, 3]>5]


array([ 8, 13, 18])

In [23]:
x=np.arange(10)
condition = (x%2==0)|(x>7)
condition

array([ True, False,  True, False,  True, False,  True, False,  True,
        True])

In [25]:
x[condition]

array([0, 2, 4, 6, 8, 9])

In [31]:
x=np.arange(10)
np.prod(x)#乘积
np.sum(x)#求和
np.cumsum(x)#前缀和
np.cumprod(x)#累乘

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
# 求取数列第?分位的数值
np.percentile(x,[25,50,75])

array([2.25, 4.5 , 6.75])

In [38]:
# 功能同上面  只不过范围为0-1直接
np.quantile(x,[0.25,0.5,0.75])

array([2.25, 4.5 , 6.75])

In [42]:
np.median(x)#中位数
np.mean(x)#平均值
np.std(x)#标准差
np.var(x)#方差


8.25

In [43]:
arr = np.arange(12).reshape(3,4)
# 加权平均
# weights 的 shape 需要和 arr 一样
weights = np.random.rand(*arr.shape)
np.average(arr, weights=weights)

5.15084729716798