## 1\. Numpy是什么？[](https://gengzhige-essay.readthedocs.io/docs/01%20%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE/1-5%20Numpy%E6%95%99%E7%A8%8B.html#id1 "永久链接至标题")

**Numerical Python** 的缩写

-   一个开源的Python科学计算库
    
-   使用numpy可以方便的使用数组、矩阵进行计算
    
-   包含线性代数、傅里叶变换、随机数生成等大量函数
    

## 2\. 为什么使用Numpy？[](https://gengzhige-essay.readthedocs.io/docs/01%20%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE/1-5%20Numpy%E6%95%99%E7%A8%8B.html#id2 "永久链接至标题")

对于同样的数值计算任务，使用numpy比直接编写python代码实现 优点：

-   代码更简洁： numpy直接以数组、矩阵为粒度计算并且支持大量的数学函数，而python需要用for循环从底层实现；
    
-   性能更高效： numpy的数组存储效率和输入输出计算性能，比python使用list好很多；numpy的大部分代码都是c语言实现的，这是numpy比python高效的原因
    

numpy是python各种数据科学类库的基础库

-   比如SciPy、Scikit-Learn、tenorflow、paddlepaddle等
    
-   如果不会numpy，这些库的深入理解都会遇到障碍

In [1]:
import numpy as np

In [3]:
#原生语法实现
def _sum(n):
    a=[i**2 for i in range(n)]
    b=[i**3 for i in range(n)]
    c=[a[i]+b[i] for i in range(n)]
    return c
print(_sum(5))

[0, 2, 12, 36, 80]


In [7]:
#numpy实现
def __sum(n):
    a=np.arange(n)**2
    b=np.arange(n)**3
    return a+b
print(__sum(5))

[ 0  2 12 36 80]


### ndarray对象：[](https://gengzhige-essay.readthedocs.io/docs/01%20%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE/1-5%20Numpy%E6%95%99%E7%A8%8B.html#ndarray "永久链接至标题")

-   numpy的核心数据结构，叫做array就是数组，array对象可以是一维数组，也可以是多维数组
    
-   python的list也可以实现相同的功能，但是array的优势在于性能好，包含数组元数据信息、大量的便捷函数
    
-   成为 Scipy、Pandas、scilit-learn、tensorflow、paddlepaddle等框架的通用底层语言
    
-   numpy的array和python的list的一个区别是它的元素必须都是同一种数据类型，这也是numpy高性能的一个原因
    

### ndarray属性[](https://gengzhige-essay.readthedocs.io/docs/01%20%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE/1-5%20Numpy%E6%95%99%E7%A8%8B.html#id4 "永久链接至标题")

-   shape 返回一个元组 表示array的形状
    
-   ndim 返回一个数字 表示array的维度的数目
    
-   size 返回一个数字 表示array中所有数据元素的数目
    
-   dtype array中元素的数据类型
    
-   itemsize 表示数组中每个元素的字节大小
    

### array本身支持的大量操作和函数[](https://gengzhige-essay.readthedocs.io/docs/01%20%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE/1-5%20Numpy%E6%95%99%E7%A8%8B.html#array "永久链接至标题")

-   直接逐元素的加减乘除等算数操作
    
-   更好用的面向多维的数组索引
    
-   求sum/mean等聚合函数
    
-   线性代数函数、比如求解逆矩阵、求解方程组
    

## 6\. 创建array的方法[](https://gengzhige-essay.readthedocs.io/docs/01%20%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE/1-5%20Numpy%E6%95%99%E7%A8%8B.html#id5 "永久链接至标题")

-   从Python的列表list和嵌套列表创建array
    
-   使用预定函数arange、linspace等创建等差数组
    
-   使用ones、ones\_like、zeros、zeros\_like、empty、empty\_like、full、full\_like、eye等函数创建
    
-   生成随机数的np.random模块创建

In [10]:
import numpy as np

x= np.array([1,2,3,4,5])
x


array([1, 2, 3, 4, 5])

In [11]:
y=np.array([
    [1,2,3,4],
    [5,6,6,7]
])
y

array([[1, 2, 3, 4],
       [5, 6, 6, 7]])

In [23]:
m,n=y.shape
print("{}   {}".format( m,n))
mm=x.shape[0]
print(mm)#返回是数组格式返回选择返回第几维，和size分清
print("数据个数",y.size)#一共有多少个数据
print("维数",y.ndim)#几维

2   4
5
数据个数 8
维数 2


### 使用np.arange(start,stop,step,dtype) 生成等差数组

-   start 表示开始的数（包含） 默认从0开始
    
-   stop 表示结束的数（不包含）
    
-   step 指定步长 默认为1
    
-   dtype 指定数据类型

In [26]:
a=np.arange(10)
b=np.arange(1,10,2,int)
b

array([1, 3, 5, 7, 9])

In [36]:
# reshape 可以改变数组的形状
# 将一维数组 改成 2行5列的 2维数组
np.arange(10).reshape(2,5)#需要被整分

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 使用np.linspace(start,stop,num,endpoint) 创建等差数组-指定数量

-   start 起始值
    
-   stop 结束值
    
-   num 要生成的等间隔样例数量，默认为50
    
-   endpoint 序列中是否包含stop值， 默认为true

In [38]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [39]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

**使用ones、ones_like、zeros、zeros_like、empty、empty_like、full、full_like、eye等函数创建**

In [55]:
a=np.ones(10)# 使用ones创建全是1的数组
print("a",a)

b=np.ones((2,4))
print("b",b)

c=np.ones_like(a)# 使用ones_like创建形状相同的数组
print("c",c)

d=np.zeros(10)
print("d",d)

e=np.zeros_like(b)
print("e",e)

# 使用empty创建未初始化的数组
# 注意：数据是未初始化的，里面的值可能是随机值不要用
f=np.empty(10)
print("f",f)

# 使用full创建指定值的数组
g=np.full(10, 666)
print("g",g)

h=np.full((2, 4), 777)
print("h",h)#同样可使用fill_like，请举一反三

# 使用 eye 函数创建 对角线的地方为1，其余的地方为0.
i=np.eye(5)
print("i",i)

a [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
b [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
c [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
d [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
e [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
f [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
g [666 666 666 666 666 666 666 666 666 666]
h [[777 777 777 777]
 [777 777 777 777]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
